name: Pull request checks

on: [pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        name: 'Run lint and tests'
        steps:
            - uses: actions/setup-node@v3
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: npm-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-node-
            - name: Install dependencies
              run: npm ci --ignore-scripts
            - name: Run lint
              run: npm run lint
            - name: Run tests
              run: npm test
